version: "3"
services:
  frontend:
    build:
      context: ./app
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - submissions-data:/data
    ports:
      - "5000:5000"

volumes:
  submissions-data:
